rm -r cexts
mkdir -p cexts/crxs cexts/zips cexts/unzips
node make_proxies.js
#delete these later, these are no longer needed
# node download_extension.js bmnlcjabgnpnenekpadlanbbkooimhnj
# node download_extension.js kbfnbcaeplbcioakkpcpgfkobkghlhen
# node download_extension.js gbkeegbaiigmenfmjfclcdgdpimamgkj
# node download_extension.js laookkfknpbbblfpciffpaejjkokdgca
# node download_extension.js ghgabhipcejejjmhhchfonmamedcbeod
# node download_extension.js mmeijimgabbpbgpdklnllpncmdofkcpn
# node download_extension.js gohjpllcolmccldfdggmamodembldgpc
# node download_extension.js nenlahapcbofgnanklpelkaejcehkggg
# node download_extension.js iginnfkhmmfhlkagcmpgofnjhanpmklb
# node download_extension.js ogdlpmhglpejoiomcodnpjnfgcpmgale
# node download_extension.js inoeonmfapjbbkmdafoankkfajkcphgd
# node download_extension.js oocalimimngaihdkbihfgmpkcpnmlaoa
# node download_extension.js jghecgabfgfdldnmbfkhmffcabddioke
# node download_extension.js pioclpoplcdbaefihamjohnefbikjilc
# node download_extension.js jldhpllghnbhlbpcmnajkpdmadaolakh
node test_popular_chrome_extensions.js jldhpllghnbhlbpcmnajkpdmadaolakh pioclpoplcdbaefihamjohnefbikjilc jghecgabfgfdldnmbfkhmffcabddioke ogdlpmhglpejoiomcodnpjnfgcpmgale iginnfkhmmfhlkagcmpgofnjhanpmklb bmnlcjabgnpnenekpadlanbbkooimhnj kbfnbcaeplbcioakkpcpgfkobkghlhen gbkeegbaiigmenfmjfclcdgdpimamgkj laookkfknpbbblfpciffpaejjkokdgca ghgabhipcejejjmhhchfonmamedcbeod mmeijimgabbpbgpdklnllpncmdofkcpn gohjpllcolmccldfdggmamodembldgpc nenlahapcbofgnanklpelkaejcehkggg
